# AI Employee - Weekly Audit
# Runs every Monday at 7:00 AM
# Generates weekly business audit and CEO briefing

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$vaultPath = Join-Path $scriptPath "AI_Employee_Vault"
$briefingsPath = Join-Path $vaultPath "Briefings"
$donePath = Join-Path $vaultPath "Done"
$logsPath = Join-Path $vaultPath "Logs"

# Ensure Briefings folder exists
if (-not (Test-Path $briefingsPath)) {
    New-Item -ItemType Directory -Path $briefingsPath | Out-Null
}

# Create log entry
$logFile = Join-Path $logsPath "scheduler.log"
$logEntry = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') - Weekly Audit triggered"
Add-Content -Path $logFile -Value $logEntry

# Get last week's completed tasks
$oneWeekAgo = (Get-Date).AddDays(-7)
$completedTasks = Get-ChildItem -Path $donePath -Filter *.md | 
    Where-Object { $_.LastWriteTime -ge $oneWeekAgo }

# Generate briefing file
$briefingDate = Get-Date -Format 'yyyy-MM-dd'
$briefingFile = Join-Path $briefingsPath "${briefingDate}_Weekly_Briefing.md"

$briefingContent = @"
# Weekly CEO Briefing

**Period:** $((Get-Date).AddDays(-7).ToString('yyyy-MM-dd')) to $((Get-Date).ToString('yyyy-MM-dd'))
**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Summary

- **Total Tasks Completed:** $($completedTasks.Count)
- **Average per Day:** $([math]::Round($completedTasks.Count / 7, 1))

## Completed This Week

"@

foreach ($task in $completedTasks) {
    $briefingContent += "- [x] $($task.BaseName)`n"
}

$briefingContent += @"

## Insights

*Review completed tasks and identify patterns*

## Action Items for Next Week

- [ ] Review pending approvals
- [ ] Follow up on outstanding items
- [ ] Plan upcoming deadlines

---
*Generated by AI Employee - Weekly Audit*
"@

Set-Content -Path $briefingFile -Value $briefingContent

$logEntry = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') - Weekly briefing created: $briefingFile"
Add-Content -Path $logFile -Value $logEntry

Write-Host "Weekly Audit completed at $(Get-Date)"
Write-Host "Briefing saved to: $briefingFile"
